name:                detect-unmatch
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/githubuser/detect-unmatch#readme
license:             BSD-3-Clause
author:              Author name here
maintainer:          example@example.com
copyright:           2026 Author name here
category:            Web
extra-source-files:
- README.md
- CHANGELOG.md

dependencies:
- base >= 4.7 && < 5
- text
- flow
- filepath
- directory
- monatone

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

executables:
  detect-unmatch:
    source-dirs:      src
    main:             Main.hs

github: githubuser/detect-unmatch
